version: '3'

services:

  reverse-proxy:
    build:
      context: ./reverse-proxy
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - mizucoffee-net-network

  status:
    build:
      context: ./status
    container_name: status
    volumes:
      - ./mount/status:/data/status/
    restart: always
    networks:
      - mizucoffee-net-network

  twiback:
    build:
      context: ./twiback
    container_name: twiback
    depends_on:
      - mongo
    restart: always
    networks:
      - mizucoffee-net-network

  prekara:
    build:
      context: ./prekara
    container_name: prekara
    depends_on:
      - mongo
    restart: always
    networks:
      - mizucoffee-net-network

  mongo:
    image: mongo
    container_name: mizucoffee-net-mongo
    restart: always
    volumes:
      - ./mount/mongodb:/data/db
    networks:
      - mizucoffee-net-network

  milacos:
    build:
      context: ./milacos
    container_name: mizucoffee-net-milacos
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./mount/milacos/nginx:/etc/nginx/conf.d/
      - ./mount/milacos/ssh:/ssh/config/
    networks:
      - mizucoffee-net-network

networks:
  mizucoffee-net-network:
