version: '3'

services:

  reverse-proxy:
    build:
      context: ./reverse-proxy
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - network

  status:
    build:
      context: ./status
    container_name: status
    volumes:
      - ./mount/status:/data/status/
    restart: always
    networks:
      - network

  twiback:
    build:
      context: ./twiback
    container_name: twiback
    depends_on:
      - mongo
    restart: always
    networks:
      - network

  prekara:
    build:
      context: ./prekara
    container_name: prekara
    depends_on:
      - mongo
    restart: always
    networks:
      - network

  mongo:
    image: mongo
    container_name: mizucoffee-net-mongo
    restart: always
    volumes:
      - ./mount/mongodb:/data/db
    networks:
      - network

networks:
  network:
