version: '3'

services:

  reverse-proxy:
    build:
      context: ./reverse-proxy
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      mizucoffee-net-network:
        ipv4_address: 10.5.0.2

  status:
    build:
      context: ./status
    container_name: status
    volumes:
      - ./mount/status:/data/status/
    restart: always
    networks:
      mizucoffee-net-network:
        ipv4_address: 10.5.0.3

  twiback:
    build:
      context: ./twiback
    container_name: twiback
    depends_on:
      - mongo
    restart: always
    networks:
      mizucoffee-net-network:
        ipv4_address: 10.5.0.4

  prekara:
    build:
      context: ./prekara
    container_name: prekara
    depends_on:
      - mongo
    restart: always
    networks:
      mizucoffee-net-network:
        ipv4_address: 10.5.0.5

  mongo:
    image: mongo
    container_name: mizucoffee-net-mongo
    restart: always
    volumes:
      - ./mount/mongodb:/data/db
    networks:
      mizucoffee-net-network:
        ipv4_address: 10.5.0.6

  milacos:
    build:
      context: ./milacos
    container_name: mizucoffee-net-milacos
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./mount/milacos/nginx:/etc/nginx/conf.d/
      - ./mount/milacos/ssh:/ssh/config/
    networks:
      mizucoffee-net-network:
        ipv4_address: 10.5.0.7

networks:
  mizucoffee-net-network:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 10.5.0.0/24
         gateway: 10.5.0.1
