version: '3'

services:
  reverse-proxy:
    build:
      context: ./reverse-proxy
    container_name: reverse-proxy
    volumes:
      - /cert/certificates:/cert
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      network:

  status:
    build:
      context: ./status
    container_name: status
    volumes:
      - ./mount/status:/data/status/
    restart: always
    networks:
      network:

  twiback:
    build:
      context: ./twiback
    container_name: twiback
    restart: always
    networks:
      network:
      db-network:

  prekara:
    build:
      context: ./prekara
    container_name: prekara
    restart: always
    networks:
      network:
      db-network:

  milacos:
    build:
      context: ./milacos
    container_name: milacos
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./mount/milacos/nginx:/etc/nginx/conf.d/
      - ./mount/milacos/ssh:/ssh/config/
    networks:
      network:
      milacos-network:
      db-network:

networks:
  network:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 10.5.0.0/24
  milacos-network:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 10.5.1.0/24
  db-network:
    external:
      name: db_network
