version: '3'

services:
  reverse-proxy:
    build:
      context: ./reverse-proxy
    container_name: reverse-proxy
    privileged: true
    ports:
      - "80:80"
      - "443:443"
    links:
      - status
      - twiback
    restart: always
  status:
    build:
      context: ./status
    container_name: status
    privileged: true
    restart: always
  twiback:
    build:
      context: ./twiback
    container_name: twiback
    privileged: true
    depends_on:
      - mongo
    links:
      - mongo
    restart: always
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongodb:/data/db
    ports:
      - "27017:27017"
